--整合h2数据库 start
INSERT INTO USER (USE_ID,USE_NAME,USE_SEX,USE_AGE,USE_ID_NO,USE_PHONE_NUM,USE_EMAIL,CREATE_TIME,MODIFY_TIME,USE_STATE) VALUES(
1,'赵一','0',20,'142323198610051234','12345678910','qe259@163.com',sysdate,sysdate,'0');
INSERT INTO USER (USE_ID,USE_NAME,USE_SEX,USE_AGE,USE_ID_NO,USE_PHONE_NUM,USE_EMAIL,CREATE_TIME,MODIFY_TIME,USE_STATE) VALUES(
2,'钱二','0',22,'142323198610051235','12345678911','qe259@164.com',sysdate,sysdate,'0');
INSERT INTO USER (USE_ID,USE_NAME,USE_SEX,USE_AGE,USE_ID_NO,USE_PHONE_NUM,USE_EMAIL,CREATE_TIME,MODIFY_TIME,USE_STATE) VALUES(
3,'孙三','1',24,'142323198610051236','12345678912','qe259@165.com',sysdate,sysdate,'0');
--整合h2数据库 end
--整合MyBatis start
INSERT INTO BOOK (BOOK_ID,PAGE_NUM,BOOK_NAME,BOOK_TYPE,BOOK_DESC,BOOK_PRICE,CREATE_TIME,MODIFY_TIME)
VALUES (1,600,'Java编程思想','0','经典的Java入门书籍',100.00,sysdate,sysdate);
INSERT INTO BOOK (BOOK_ID,PAGE_NUM,BOOK_NAME,BOOK_TYPE,BOOK_DESC,BOOK_PRICE,CREATE_TIME,MODIFY_TIME)
VALUES (2,350,'深入理解Java虚拟机','0','经典的Java虚拟机入门书籍',56.00,sysdate,sysdate);
INSERT INTO BOOK (BOOK_ID,PAGE_NUM,BOOK_NAME,BOOK_TYPE,BOOK_DESC,BOOK_PRICE,CREATE_TIME,MODIFY_TIME)
VALUES (3,300,'西游记','1','四大名著之一',25.00,sysdate,sysdate);
INSERT INTO BOOK (BOOK_ID,PAGE_NUM,BOOK_NAME,BOOK_TYPE,BOOK_DESC,BOOK_PRICE,CREATE_TIME,MODIFY_TIME)
VALUES (4,1000,'红楼梦','1','四大名著之一',100.00,sysdate,sysdate);
--整合MyBatis end
--整合MyBatis-plus start
INSERT INTO ANIMAL(ID,NAME,TYPE,SEX,MASTER)
VALUES (1,'花花',1,1,'小花');
INSERT INTO ANIMAL(ID,NAME,TYPE,SEX,MASTER)
VALUES (2,'毛毛',2,1,'小毛');
INSERT INTO ANIMAL(ID,NAME,TYPE,SEX,MASTER)
VALUES (3,'勾勾',3,1,'小勾');
INSERT INTO ANIMAL(ID,NAME,TYPE,SEX,MASTER)
VALUES (4,'龙龙',4,1,'小龙');
INSERT INTO ANIMAL(ID,NAME,TYPE,SEX,MASTER)
VALUES (5,'塔塔',5,1,'小塔');
--整合MyBatis-plus end
