spring:
  datasource: #h2-config,database-config
    driver-class-name: org.h2.Driver  #配置JDBC Driver
    url: jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE #配置h2数据库的连接地址
    username: sa  #配置数据库用户名
    password: sa  #配置数据库密码
    schema: classpath:db/schema.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    data: classpath:db/data.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
  h2: #h2-console-config
    console:
      path: /h2  #h2数据库的管理链接地址为/h2，默认为/h2-console
      enabled: true  #设置h2内存管理器是否可用，默认true，可用
      settings:
        web-allow-others: true #进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
  jpa: #JPA-config
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath*:/repository/*.xml
  type-handlers-package: com.dh.springbootintegration.mybatis.handler
  type-aliases-package: com.dh.springbootintegration.mybatis.entity
mybatis-plus:
  mapper-locations: classpath*:/repository/*.xml
  type-aliases-package: com.dh.springbootintegration.mybatisplus.entity,com.dh.springbootintegration.mybatis.entity
  type-aliases-super-type: java.lang.Object
  type-enums-package: com.dh.springbootintegration.mybatisplus.enums