spring:
  datasource: #h2-config,database-config
    driver-class-name: org.h2.Driver  #配置JDBC Driver
    url: jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE #配置h2数据库的连接地址
    username: sa  #配置数据库用户名
    password: sa  #配置数据库密码
    schema: classpath:db/schema.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    data: classpath:db/data.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
  h2: #h2-console-config
    console:
      path: /h2  #h2数据库的管理链接地址为/h2，默认为/h2-console
      enabled: true  #设置h2内存管理器是否可用，默认true，可用
      settings:
        web-allow-others: true #进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
  jpa: #JPA-config
    hibernate:
      ddl-auto: update
  freemarker:
    cache: false #设置页面缓存，默认开启
    suffix: .ftl #设置模板后缀名
    enabled: true #设置是否启用当前模板
    content-type: text/html #设置文档类型
    request-context-attribute: request
    template-loader-path: classpath:/templates/ #设置模板文件加载路径
    charset: UTF-8 #设置模板文件编码格式
    expose-request-attributes: true #暴露request属性，默认false
    expose-session-attributes: true #暴露session属性，默认false
  thymeleaf:
    cache: false #设置页面缓存，默认开启
    encoding: UTF-8 #设置模板页面编码格式
    enabled: false #设置关闭当前模板
    mode: HTML #设置模板文件模式
    prefix: classpath:/templates/ #设置模板文件前缀
    suffix: .html #设置模板文件后缀
    servlet:
      content-type: text/html #设置文档类型

mybatis: #mybatis-config
  mapper-locations: classpath*:/repository/*.xml
  type-handlers-package: com.dh.springbootintegration.mybatis.handler
  type-aliases-package: com.dh.springbootintegration.mybatis.entity
mybatis-plus: #mybatis-plus-config
  mapper-locations: classpath*:/repository/*.xml
  type-aliases-package: com.dh.springbootintegration.mybatisplus.entity,com.dh.springbootintegration.mybatis.entity
  type-aliases-super-type: java.lang.Object
  type-enums-package: com.dh.springbootintegration.mybatisplus.enums
  global-config:
      db-config: #设置逻辑删除
        logic-delete-value: 1
        logic-not-delete-value: 0